# Generated by Django 4.2.4 on 2023-08-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app_1', '0001_initial'),
    ]

    operations = [
    ]
