# Generated by Django 4.2.4 on 2023-08-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app_1', '0002_auto_20230819_1949'),
    ]

    operations = [
    ]
